services:
  liquor_container:
    image: "ryeager12/liquor-tracker:liquor"
    pull_policy: always
    env_file:
      - ../.env
    volumes:
      - ../config:/config
    networks:
      - compose_network
    restart: always


networks:
  compose_network:
