name: Python Application

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Python App Docker Test
        id: python-app
        uses: ./.github/actions/docker-python-action
        with:
          version: v2.0.0
      - name: Get Docker results
        run: echo "${{ steps.python-app.outputs.result }}"

  trigger-docker-build:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Trigger a dependent workflow
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/docker-build.yml/dispatches \
            -d '{"ref":"main", "inputs": {"run": "true", "branch": "${{ github.ref_name }}"}}'
